### ISSUE TITLE
missing ssl library link flag

### ISSUE THREAD

**Issue by iknowmarkers** [orkim/dh1080_tcl#1]
the last lines in the make file are missing the needed library ssl
``gcc -static -shared DH1080_tcl.o DH1080.o base64.o -o DH1080_tcl.so``
should be
``gcc -static -shared DH1080_tcl.o DH1080.o base64.o -lssl -lcrypto -o DH1080_tcl.so``
DH1080.c includes a openssl header file named sha.h which makes openssl library required for this plugin to work

**Comment by orkim** [comment]
Thank you!  Updates pushed.
